# Generated by Django 2.2.11 on 2020-05-28 09:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='taskDetails',
            fields=[
                ('taskId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('custTaskId', models.CharField(max_length=100)),
                ('userId', models.CharField(max_length=100)),
                ('taskName', models.TextField()),
                ('taskDescription', models.TextField()),
                ('taskCategory', models.CharField(max_length=100)),
                ('taskSubCategory', models.CharField(max_length=100)),
                ('taskAttachment1', models.URLField(blank=True)),
                ('taskAttachment2', models.URLField(blank=True)),
                ('taskStatus', models.CharField(max_length=50)),
                ('creationTime', models.DateTimeField(default=datetime.datetime(2020, 5, 28, 9, 2, 0, 637785, tzinfo=utc))),
                ('expertAssigned', models.CharField(max_length=200)),
                ('solutionDescription', models.TextField()),
                ('solAttachment1', models.URLField(blank=True)),
                ('solAttachment2', models.URLField(blank=True)),
                ('isPaid', models.BooleanField(default=False)),
            ],
        ),
    ]
